//! Generated embed table: SVG stem to compiled-in bytes for the
//! Catppuccin Mocha file-icon set. Generated; do not edit by hand.

/// Every vendored icon, as `(stem, svg_bytes)`, sorted by stem so a
/// binary search can resolve a stem to its bytes.
pub const ICON_BYTES: &[(&str, &[u8])] = &[
    ("3d", include_bytes!("../../assets/file-icons/mocha/3d.svg")),
    (
        "_file",
        include_bytes!("../../assets/file-icons/mocha/_file.svg"),
    ),
    (
        "_folder",
        include_bytes!("../../assets/file-icons/mocha/_folder.svg"),
    ),
    (
        "_folder_open",
        include_bytes!("../../assets/file-icons/mocha/_folder_open.svg"),
    ),
    (
        "adobe-ae",
        include_bytes!("../../assets/file-icons/mocha/adobe-ae.svg"),
    ),
    (
        "adobe-ai",
        include_bytes!("../../assets/file-icons/mocha/adobe-ai.svg"),
    ),
    (
        "adobe-id",
        include_bytes!("../../assets/file-icons/mocha/adobe-id.svg"),
    ),
    (
        "adobe-ps",
        include_bytes!("../../assets/file-icons/mocha/adobe-ps.svg"),
    ),
    (
        "adobe-xd",
        include_bytes!("../../assets/file-icons/mocha/adobe-xd.svg"),
    ),
    (
        "adonis",
        include_bytes!("../../assets/file-icons/mocha/adonis.svg"),
    ),
    (
        "alex",
        include_bytes!("../../assets/file-icons/mocha/alex.svg"),
    ),
    (
        "amber",
        include_bytes!("../../assets/file-icons/mocha/amber.svg"),
    ),
    (
        "android",
        include_bytes!("../../assets/file-icons/mocha/android.svg"),
    ),
    (
        "angular",
        include_bytes!("../../assets/file-icons/mocha/angular.svg"),
    ),
    (
        "ansible-lint",
        include_bytes!("../../assets/file-icons/mocha/ansible-lint.svg"),
    ),
    (
        "antlr",
        include_bytes!("../../assets/file-icons/mocha/antlr.svg"),
    ),
    (
        "apache",
        include_bytes!("../../assets/file-icons/mocha/apache.svg"),
    ),
    (
        "api-blueprint",
        include_bytes!("../../assets/file-icons/mocha/api-blueprint.svg"),
    ),
    (
        "apollo",
        include_bytes!("../../assets/file-icons/mocha/apollo.svg"),
    ),
    (
        "apple",
        include_bytes!("../../assets/file-icons/mocha/apple.svg"),
    ),
    (
        "arduino",
        include_bytes!("../../assets/file-icons/mocha/arduino.svg"),
    ),
    (
        "asciidoc",
        include_bytes!("../../assets/file-icons/mocha/asciidoc.svg"),
    ),
    (
        "assembly",
        include_bytes!("../../assets/file-icons/mocha/assembly.svg"),
    ),
    (
        "astro",
        include_bytes!("../../assets/file-icons/mocha/astro.svg"),
    ),
    (
        "astro-config",
        include_bytes!("../../assets/file-icons/mocha/astro-config.svg"),
    ),
    (
        "audio",
        include_bytes!("../../assets/file-icons/mocha/audio.svg"),
    ),
    (
        "autohotkey",
        include_bytes!("../../assets/file-icons/mocha/autohotkey.svg"),
    ),
    (
        "azure-pipelines",
        include_bytes!("../../assets/file-icons/mocha/azure-pipelines.svg"),
    ),
    (
        "babel",
        include_bytes!("../../assets/file-icons/mocha/babel.svg"),
    ),
    (
        "bash",
        include_bytes!("../../assets/file-icons/mocha/bash.svg"),
    ),
    (
        "batch",
        include_bytes!("../../assets/file-icons/mocha/batch.svg"),
    ),
    (
        "bazel",
        include_bytes!("../../assets/file-icons/mocha/bazel.svg"),
    ),
    (
        "benchmark",
        include_bytes!("../../assets/file-icons/mocha/benchmark.svg"),
    ),
    (
        "bicep",
        include_bytes!("../../assets/file-icons/mocha/bicep.svg"),
    ),
    (
        "binary",
        include_bytes!("../../assets/file-icons/mocha/binary.svg"),
    ),
    (
        "biome",
        include_bytes!("../../assets/file-icons/mocha/biome.svg"),
    ),
    (
        "bitbucket",
        include_bytes!("../../assets/file-icons/mocha/bitbucket.svg"),
    ),
    (
        "blink",
        include_bytes!("../../assets/file-icons/mocha/blink.svg"),
    ),
    (
        "blitz",
        include_bytes!("../../assets/file-icons/mocha/blitz.svg"),
    ),
    (
        "bower",
        include_bytes!("../../assets/file-icons/mocha/bower.svg"),
    ),
    (
        "browserslist",
        include_bytes!("../../assets/file-icons/mocha/browserslist.svg"),
    ),
    (
        "bun",
        include_bytes!("../../assets/file-icons/mocha/bun.svg"),
    ),
    (
        "bun-lock",
        include_bytes!("../../assets/file-icons/mocha/bun-lock.svg"),
    ),
    ("c", include_bytes!("../../assets/file-icons/mocha/c.svg")),
    (
        "c-header",
        include_bytes!("../../assets/file-icons/mocha/c-header.svg"),
    ),
    (
        "cabal",
        include_bytes!("../../assets/file-icons/mocha/cabal.svg"),
    ),
    (
        "caddy",
        include_bytes!("../../assets/file-icons/mocha/caddy.svg"),
    ),
    (
        "capacitor",
        include_bytes!("../../assets/file-icons/mocha/capacitor.svg"),
    ),
    (
        "cargo",
        include_bytes!("../../assets/file-icons/mocha/cargo.svg"),
    ),
    (
        "cargo-lock",
        include_bytes!("../../assets/file-icons/mocha/cargo-lock.svg"),
    ),
    (
        "certificate",
        include_bytes!("../../assets/file-icons/mocha/certificate.svg"),
    ),
    (
        "changelog",
        include_bytes!("../../assets/file-icons/mocha/changelog.svg"),
    ),
    (
        "circle-ci",
        include_bytes!("../../assets/file-icons/mocha/circle-ci.svg"),
    ),
    (
        "clojure",
        include_bytes!("../../assets/file-icons/mocha/clojure.svg"),
    ),
    (
        "cmake",
        include_bytes!("../../assets/file-icons/mocha/cmake.svg"),
    ),
    (
        "cobol",
        include_bytes!("../../assets/file-icons/mocha/cobol.svg"),
    ),
    (
        "code-climate",
        include_bytes!("../../assets/file-icons/mocha/code-climate.svg"),
    ),
    (
        "code-of-conduct",
        include_bytes!("../../assets/file-icons/mocha/code-of-conduct.svg"),
    ),
    (
        "codeowners",
        include_bytes!("../../assets/file-icons/mocha/codeowners.svg"),
    ),
    (
        "coffeescript",
        include_bytes!("../../assets/file-icons/mocha/coffeescript.svg"),
    ),
    (
        "commitlint",
        include_bytes!("../../assets/file-icons/mocha/commitlint.svg"),
    ),
    (
        "config",
        include_bytes!("../../assets/file-icons/mocha/config.svg"),
    ),
    (
        "contributing",
        include_bytes!("../../assets/file-icons/mocha/contributing.svg"),
    ),
    (
        "cpp",
        include_bytes!("../../assets/file-icons/mocha/cpp.svg"),
    ),
    (
        "cpp-header",
        include_bytes!("../../assets/file-icons/mocha/cpp-header.svg"),
    ),
    (
        "crystal",
        include_bytes!("../../assets/file-icons/mocha/crystal.svg"),
    ),
    (
        "csharp",
        include_bytes!("../../assets/file-icons/mocha/csharp.svg"),
    ),
    (
        "cspell",
        include_bytes!("../../assets/file-icons/mocha/cspell.svg"),
    ),
    (
        "css",
        include_bytes!("../../assets/file-icons/mocha/css.svg"),
    ),
    (
        "css-map",
        include_bytes!("../../assets/file-icons/mocha/css-map.svg"),
    ),
    (
        "csv",
        include_bytes!("../../assets/file-icons/mocha/csv.svg"),
    ),
    (
        "cucumber",
        include_bytes!("../../assets/file-icons/mocha/cucumber.svg"),
    ),
    (
        "cuda",
        include_bytes!("../../assets/file-icons/mocha/cuda.svg"),
    ),
    (
        "cue",
        include_bytes!("../../assets/file-icons/mocha/cue.svg"),
    ),
    (
        "cursor",
        include_bytes!("../../assets/file-icons/mocha/cursor.svg"),
    ),
    (
        "cursor-ignore",
        include_bytes!("../../assets/file-icons/mocha/cursor-ignore.svg"),
    ),
    (
        "cypress",
        include_bytes!("../../assets/file-icons/mocha/cypress.svg"),
    ),
    ("d", include_bytes!("../../assets/file-icons/mocha/d.svg")),
    (
        "darklua",
        include_bytes!("../../assets/file-icons/mocha/darklua.svg"),
    ),
    (
        "dart",
        include_bytes!("../../assets/file-icons/mocha/dart.svg"),
    ),
    (
        "dart-generated",
        include_bytes!("../../assets/file-icons/mocha/dart-generated.svg"),
    ),
    (
        "database",
        include_bytes!("../../assets/file-icons/mocha/database.svg"),
    ),
    (
        "deno",
        include_bytes!("../../assets/file-icons/mocha/deno.svg"),
    ),
    (
        "deno_lock",
        include_bytes!("../../assets/file-icons/mocha/deno_lock.svg"),
    ),
    (
        "dependabot",
        include_bytes!("../../assets/file-icons/mocha/dependabot.svg"),
    ),
    (
        "devcontainer",
        include_bytes!("../../assets/file-icons/mocha/devcontainer.svg"),
    ),
    (
        "dhall",
        include_bytes!("../../assets/file-icons/mocha/dhall.svg"),
    ),
    (
        "diff",
        include_bytes!("../../assets/file-icons/mocha/diff.svg"),
    ),
    (
        "django",
        include_bytes!("../../assets/file-icons/mocha/django.svg"),
    ),
    (
        "docker",
        include_bytes!("../../assets/file-icons/mocha/docker.svg"),
    ),
    (
        "docker-compose",
        include_bytes!("../../assets/file-icons/mocha/docker-compose.svg"),
    ),
    (
        "docker-ignore",
        include_bytes!("../../assets/file-icons/mocha/docker-ignore.svg"),
    ),
    (
        "docusaurus",
        include_bytes!("../../assets/file-icons/mocha/docusaurus.svg"),
    ),
    (
        "drawio",
        include_bytes!("../../assets/file-icons/mocha/drawio.svg"),
    ),
    (
        "drizzle-orm",
        include_bytes!("../../assets/file-icons/mocha/drizzle-orm.svg"),
    ),
    (
        "dub",
        include_bytes!("../../assets/file-icons/mocha/dub.svg"),
    ),
    (
        "dub-selections",
        include_bytes!("../../assets/file-icons/mocha/dub-selections.svg"),
    ),
    (
        "editorconfig",
        include_bytes!("../../assets/file-icons/mocha/editorconfig.svg"),
    ),
    (
        "ejs",
        include_bytes!("../../assets/file-icons/mocha/ejs.svg"),
    ),
    (
        "eleventy",
        include_bytes!("../../assets/file-icons/mocha/eleventy.svg"),
    ),
    (
        "elixir",
        include_bytes!("../../assets/file-icons/mocha/elixir.svg"),
    ),
    (
        "elm",
        include_bytes!("../../assets/file-icons/mocha/elm.svg"),
    ),
    (
        "ember",
        include_bytes!("../../assets/file-icons/mocha/ember.svg"),
    ),
    (
        "env",
        include_bytes!("../../assets/file-icons/mocha/env.svg"),
    ),
    (
        "envrc",
        include_bytes!("../../assets/file-icons/mocha/envrc.svg"),
    ),
    (
        "erlang",
        include_bytes!("../../assets/file-icons/mocha/erlang.svg"),
    ),
    (
        "esbuild",
        include_bytes!("../../assets/file-icons/mocha/esbuild.svg"),
    ),
    (
        "eslint",
        include_bytes!("../../assets/file-icons/mocha/eslint.svg"),
    ),
    (
        "eslint-ignore",
        include_bytes!("../../assets/file-icons/mocha/eslint-ignore.svg"),
    ),
    (
        "exe",
        include_bytes!("../../assets/file-icons/mocha/exe.svg"),
    ),
    (
        "fastlane",
        include_bytes!("../../assets/file-icons/mocha/fastlane.svg"),
    ),
    (
        "favicon",
        include_bytes!("../../assets/file-icons/mocha/favicon.svg"),
    ),
    (
        "figma",
        include_bytes!("../../assets/file-icons/mocha/figma.svg"),
    ),
    (
        "firebase",
        include_bytes!("../../assets/file-icons/mocha/firebase.svg"),
    ),
    (
        "flutter",
        include_bytes!("../../assets/file-icons/mocha/flutter.svg"),
    ),
    (
        "folder_admin",
        include_bytes!("../../assets/file-icons/mocha/folder_admin.svg"),
    ),
    (
        "folder_admin_open",
        include_bytes!("../../assets/file-icons/mocha/folder_admin_open.svg"),
    ),
    (
        "folder_android",
        include_bytes!("../../assets/file-icons/mocha/folder_android.svg"),
    ),
    (
        "folder_android_open",
        include_bytes!("../../assets/file-icons/mocha/folder_android_open.svg"),
    ),
    (
        "folder_animation",
        include_bytes!("../../assets/file-icons/mocha/folder_animation.svg"),
    ),
    (
        "folder_animation_open",
        include_bytes!("../../assets/file-icons/mocha/folder_animation_open.svg"),
    ),
    (
        "folder_api",
        include_bytes!("../../assets/file-icons/mocha/folder_api.svg"),
    ),
    (
        "folder_api_open",
        include_bytes!("../../assets/file-icons/mocha/folder_api_open.svg"),
    ),
    (
        "folder_app",
        include_bytes!("../../assets/file-icons/mocha/folder_app.svg"),
    ),
    (
        "folder_app_open",
        include_bytes!("../../assets/file-icons/mocha/folder_app_open.svg"),
    ),
    (
        "folder_assets",
        include_bytes!("../../assets/file-icons/mocha/folder_assets.svg"),
    ),
    (
        "folder_assets_open",
        include_bytes!("../../assets/file-icons/mocha/folder_assets_open.svg"),
    ),
    (
        "folder_audio",
        include_bytes!("../../assets/file-icons/mocha/folder_audio.svg"),
    ),
    (
        "folder_audio_open",
        include_bytes!("../../assets/file-icons/mocha/folder_audio_open.svg"),
    ),
    (
        "folder_audit",
        include_bytes!("../../assets/file-icons/mocha/folder_audit.svg"),
    ),
    (
        "folder_audit_open",
        include_bytes!("../../assets/file-icons/mocha/folder_audit_open.svg"),
    ),
    (
        "folder_aws",
        include_bytes!("../../assets/file-icons/mocha/folder_aws.svg"),
    ),
    (
        "folder_aws_open",
        include_bytes!("../../assets/file-icons/mocha/folder_aws_open.svg"),
    ),
    (
        "folder_azure-devops",
        include_bytes!("../../assets/file-icons/mocha/folder_azure-devops.svg"),
    ),
    (
        "folder_azure-devops_open",
        include_bytes!("../../assets/file-icons/mocha/folder_azure-devops_open.svg"),
    ),
    (
        "folder_azure-pipelines",
        include_bytes!("../../assets/file-icons/mocha/folder_azure-pipelines.svg"),
    ),
    (
        "folder_azure-pipelines_open",
        include_bytes!("../../assets/file-icons/mocha/folder_azure-pipelines_open.svg"),
    ),
    (
        "folder_benchmark",
        include_bytes!("../../assets/file-icons/mocha/folder_benchmark.svg"),
    ),
    (
        "folder_benchmark_open",
        include_bytes!("../../assets/file-icons/mocha/folder_benchmark_open.svg"),
    ),
    (
        "folder_caddy",
        include_bytes!("../../assets/file-icons/mocha/folder_caddy.svg"),
    ),
    (
        "folder_caddy_open",
        include_bytes!("../../assets/file-icons/mocha/folder_caddy_open.svg"),
    ),
    (
        "folder_cargo",
        include_bytes!("../../assets/file-icons/mocha/folder_cargo.svg"),
    ),
    (
        "folder_cargo_open",
        include_bytes!("../../assets/file-icons/mocha/folder_cargo_open.svg"),
    ),
    (
        "folder_circle-ci",
        include_bytes!("../../assets/file-icons/mocha/folder_circle-ci.svg"),
    ),
    (
        "folder_circle-ci_open",
        include_bytes!("../../assets/file-icons/mocha/folder_circle-ci_open.svg"),
    ),
    (
        "folder_client",
        include_bytes!("../../assets/file-icons/mocha/folder_client.svg"),
    ),
    (
        "folder_client_open",
        include_bytes!("../../assets/file-icons/mocha/folder_client_open.svg"),
    ),
    (
        "folder_cloud",
        include_bytes!("../../assets/file-icons/mocha/folder_cloud.svg"),
    ),
    (
        "folder_cloud_open",
        include_bytes!("../../assets/file-icons/mocha/folder_cloud_open.svg"),
    ),
    (
        "folder_command",
        include_bytes!("../../assets/file-icons/mocha/folder_command.svg"),
    ),
    (
        "folder_command_open",
        include_bytes!("../../assets/file-icons/mocha/folder_command_open.svg"),
    ),
    (
        "folder_components",
        include_bytes!("../../assets/file-icons/mocha/folder_components.svg"),
    ),
    (
        "folder_components_open",
        include_bytes!("../../assets/file-icons/mocha/folder_components_open.svg"),
    ),
    (
        "folder_composables",
        include_bytes!("../../assets/file-icons/mocha/folder_composables.svg"),
    ),
    (
        "folder_composables_open",
        include_bytes!("../../assets/file-icons/mocha/folder_composables_open.svg"),
    ),
    (
        "folder_config",
        include_bytes!("../../assets/file-icons/mocha/folder_config.svg"),
    ),
    (
        "folder_config_open",
        include_bytes!("../../assets/file-icons/mocha/folder_config_open.svg"),
    ),
    (
        "folder_connection",
        include_bytes!("../../assets/file-icons/mocha/folder_connection.svg"),
    ),
    (
        "folder_connection_open",
        include_bytes!("../../assets/file-icons/mocha/folder_connection_open.svg"),
    ),
    (
        "folder_constant",
        include_bytes!("../../assets/file-icons/mocha/folder_constant.svg"),
    ),
    (
        "folder_constant_open",
        include_bytes!("../../assets/file-icons/mocha/folder_constant_open.svg"),
    ),
    (
        "folder_content",
        include_bytes!("../../assets/file-icons/mocha/folder_content.svg"),
    ),
    (
        "folder_content_open",
        include_bytes!("../../assets/file-icons/mocha/folder_content_open.svg"),
    ),
    (
        "folder_controllers",
        include_bytes!("../../assets/file-icons/mocha/folder_controllers.svg"),
    ),
    (
        "folder_controllers_open",
        include_bytes!("../../assets/file-icons/mocha/folder_controllers_open.svg"),
    ),
    (
        "folder_core",
        include_bytes!("../../assets/file-icons/mocha/folder_core.svg"),
    ),
    (
        "folder_core_open",
        include_bytes!("../../assets/file-icons/mocha/folder_core_open.svg"),
    ),
    (
        "folder_coverage",
        include_bytes!("../../assets/file-icons/mocha/folder_coverage.svg"),
    ),
    (
        "folder_coverage_open",
        include_bytes!("../../assets/file-icons/mocha/folder_coverage_open.svg"),
    ),
    (
        "folder_cursor",
        include_bytes!("../../assets/file-icons/mocha/folder_cursor.svg"),
    ),
    (
        "folder_cursor_open",
        include_bytes!("../../assets/file-icons/mocha/folder_cursor_open.svg"),
    ),
    (
        "folder_cypress",
        include_bytes!("../../assets/file-icons/mocha/folder_cypress.svg"),
    ),
    (
        "folder_cypress_open",
        include_bytes!("../../assets/file-icons/mocha/folder_cypress_open.svg"),
    ),
    (
        "folder_database",
        include_bytes!("../../assets/file-icons/mocha/folder_database.svg"),
    ),
    (
        "folder_database_open",
        include_bytes!("../../assets/file-icons/mocha/folder_database_open.svg"),
    ),
    (
        "folder_debug",
        include_bytes!("../../assets/file-icons/mocha/folder_debug.svg"),
    ),
    (
        "folder_debug_open",
        include_bytes!("../../assets/file-icons/mocha/folder_debug_open.svg"),
    ),
    (
        "folder_devcontainer",
        include_bytes!("../../assets/file-icons/mocha/folder_devcontainer.svg"),
    ),
    (
        "folder_devcontainer_open",
        include_bytes!("../../assets/file-icons/mocha/folder_devcontainer_open.svg"),
    ),
    (
        "folder_direnv",
        include_bytes!("../../assets/file-icons/mocha/folder_direnv.svg"),
    ),
    (
        "folder_direnv_open",
        include_bytes!("../../assets/file-icons/mocha/folder_direnv_open.svg"),
    ),
    (
        "folder_dist",
        include_bytes!("../../assets/file-icons/mocha/folder_dist.svg"),
    ),
    (
        "folder_dist_open",
        include_bytes!("../../assets/file-icons/mocha/folder_dist_open.svg"),
    ),
    (
        "folder_docker",
        include_bytes!("../../assets/file-icons/mocha/folder_docker.svg"),
    ),
    (
        "folder_docker_open",
        include_bytes!("../../assets/file-icons/mocha/folder_docker_open.svg"),
    ),
    (
        "folder_docs",
        include_bytes!("../../assets/file-icons/mocha/folder_docs.svg"),
    ),
    (
        "folder_docs_open",
        include_bytes!("../../assets/file-icons/mocha/folder_docs_open.svg"),
    ),
    (
        "folder_download",
        include_bytes!("../../assets/file-icons/mocha/folder_download.svg"),
    ),
    (
        "folder_download_open",
        include_bytes!("../../assets/file-icons/mocha/folder_download_open.svg"),
    ),
    (
        "folder_drizzle-orm",
        include_bytes!("../../assets/file-icons/mocha/folder_drizzle-orm.svg"),
    ),
    (
        "folder_drizzle-orm_open",
        include_bytes!("../../assets/file-icons/mocha/folder_drizzle-orm_open.svg"),
    ),
    (
        "folder_examples",
        include_bytes!("../../assets/file-icons/mocha/folder_examples.svg"),
    ),
    (
        "folder_examples_open",
        include_bytes!("../../assets/file-icons/mocha/folder_examples_open.svg"),
    ),
    (
        "folder_fastlane",
        include_bytes!("../../assets/file-icons/mocha/folder_fastlane.svg"),
    ),
    (
        "folder_fastlane_open",
        include_bytes!("../../assets/file-icons/mocha/folder_fastlane_open.svg"),
    ),
    (
        "folder_firebase",
        include_bytes!("../../assets/file-icons/mocha/folder_firebase.svg"),
    ),
    (
        "folder_firebase_open",
        include_bytes!("../../assets/file-icons/mocha/folder_firebase_open.svg"),
    ),
    (
        "folder_fonts",
        include_bytes!("../../assets/file-icons/mocha/folder_fonts.svg"),
    ),
    (
        "folder_fonts_open",
        include_bytes!("../../assets/file-icons/mocha/folder_fonts_open.svg"),
    ),
    (
        "folder_forgejo",
        include_bytes!("../../assets/file-icons/mocha/folder_forgejo.svg"),
    ),
    (
        "folder_forgejo_open",
        include_bytes!("../../assets/file-icons/mocha/folder_forgejo_open.svg"),
    ),
    (
        "folder_functions",
        include_bytes!("../../assets/file-icons/mocha/folder_functions.svg"),
    ),
    (
        "folder_functions_open",
        include_bytes!("../../assets/file-icons/mocha/folder_functions_open.svg"),
    ),
    (
        "folder_fvm",
        include_bytes!("../../assets/file-icons/mocha/folder_fvm.svg"),
    ),
    (
        "folder_fvm_open",
        include_bytes!("../../assets/file-icons/mocha/folder_fvm_open.svg"),
    ),
    (
        "folder_git",
        include_bytes!("../../assets/file-icons/mocha/folder_git.svg"),
    ),
    (
        "folder_git_open",
        include_bytes!("../../assets/file-icons/mocha/folder_git_open.svg"),
    ),
    (
        "folder_github",
        include_bytes!("../../assets/file-icons/mocha/folder_github.svg"),
    ),
    (
        "folder_github_open",
        include_bytes!("../../assets/file-icons/mocha/folder_github_open.svg"),
    ),
    (
        "folder_gitlab",
        include_bytes!("../../assets/file-icons/mocha/folder_gitlab.svg"),
    ),
    (
        "folder_gitlab_open",
        include_bytes!("../../assets/file-icons/mocha/folder_gitlab_open.svg"),
    ),
    (
        "folder_gradle",
        include_bytes!("../../assets/file-icons/mocha/folder_gradle.svg"),
    ),
    (
        "folder_gradle_open",
        include_bytes!("../../assets/file-icons/mocha/folder_gradle_open.svg"),
    ),
    (
        "folder_graphql",
        include_bytes!("../../assets/file-icons/mocha/folder_graphql.svg"),
    ),
    (
        "folder_graphql_open",
        include_bytes!("../../assets/file-icons/mocha/folder_graphql_open.svg"),
    ),
    (
        "folder_hooks",
        include_bytes!("../../assets/file-icons/mocha/folder_hooks.svg"),
    ),
    (
        "folder_hooks_open",
        include_bytes!("../../assets/file-icons/mocha/folder_hooks_open.svg"),
    ),
    (
        "folder_husky",
        include_bytes!("../../assets/file-icons/mocha/folder_husky.svg"),
    ),
    (
        "folder_husky_open",
        include_bytes!("../../assets/file-icons/mocha/folder_husky_open.svg"),
    ),
    (
        "folder_images",
        include_bytes!("../../assets/file-icons/mocha/folder_images.svg"),
    ),
    (
        "folder_images_open",
        include_bytes!("../../assets/file-icons/mocha/folder_images_open.svg"),
    ),
    (
        "folder_include",
        include_bytes!("../../assets/file-icons/mocha/folder_include.svg"),
    ),
    (
        "folder_include_open",
        include_bytes!("../../assets/file-icons/mocha/folder_include_open.svg"),
    ),
    (
        "folder_intellij",
        include_bytes!("../../assets/file-icons/mocha/folder_intellij.svg"),
    ),
    (
        "folder_intellij_open",
        include_bytes!("../../assets/file-icons/mocha/folder_intellij_open.svg"),
    ),
    (
        "folder_javascript",
        include_bytes!("../../assets/file-icons/mocha/folder_javascript.svg"),
    ),
    (
        "folder_javascript_open",
        include_bytes!("../../assets/file-icons/mocha/folder_javascript_open.svg"),
    ),
    (
        "folder_kubernetes",
        include_bytes!("../../assets/file-icons/mocha/folder_kubernetes.svg"),
    ),
    (
        "folder_kubernetes_open",
        include_bytes!("../../assets/file-icons/mocha/folder_kubernetes_open.svg"),
    ),
    (
        "folder_layouts",
        include_bytes!("../../assets/file-icons/mocha/folder_layouts.svg"),
    ),
    (
        "folder_layouts_open",
        include_bytes!("../../assets/file-icons/mocha/folder_layouts_open.svg"),
    ),
    (
        "folder_lib",
        include_bytes!("../../assets/file-icons/mocha/folder_lib.svg"),
    ),
    (
        "folder_lib_open",
        include_bytes!("../../assets/file-icons/mocha/folder_lib_open.svg"),
    ),
    (
        "folder_linux",
        include_bytes!("../../assets/file-icons/mocha/folder_linux.svg"),
    ),
    (
        "folder_linux_open",
        include_bytes!("../../assets/file-icons/mocha/folder_linux_open.svg"),
    ),
    (
        "folder_locales",
        include_bytes!("../../assets/file-icons/mocha/folder_locales.svg"),
    ),
    (
        "folder_locales_open",
        include_bytes!("../../assets/file-icons/mocha/folder_locales_open.svg"),
    ),
    (
        "folder_luau",
        include_bytes!("../../assets/file-icons/mocha/folder_luau.svg"),
    ),
    (
        "folder_luau_open",
        include_bytes!("../../assets/file-icons/mocha/folder_luau_open.svg"),
    ),
    (
        "folder_lune",
        include_bytes!("../../assets/file-icons/mocha/folder_lune.svg"),
    ),
    (
        "folder_lune_open",
        include_bytes!("../../assets/file-icons/mocha/folder_lune_open.svg"),
    ),
    (
        "folder_macos",
        include_bytes!("../../assets/file-icons/mocha/folder_macos.svg"),
    ),
    (
        "folder_macos_open",
        include_bytes!("../../assets/file-icons/mocha/folder_macos_open.svg"),
    ),
    (
        "folder_messages",
        include_bytes!("../../assets/file-icons/mocha/folder_messages.svg"),
    ),
    (
        "folder_messages_open",
        include_bytes!("../../assets/file-icons/mocha/folder_messages_open.svg"),
    ),
    (
        "folder_middleware",
        include_bytes!("../../assets/file-icons/mocha/folder_middleware.svg"),
    ),
    (
        "folder_middleware_open",
        include_bytes!("../../assets/file-icons/mocha/folder_middleware_open.svg"),
    ),
    (
        "folder_mocks",
        include_bytes!("../../assets/file-icons/mocha/folder_mocks.svg"),
    ),
    (
        "folder_mocks_open",
        include_bytes!("../../assets/file-icons/mocha/folder_mocks_open.svg"),
    ),
    (
        "folder_moonrepo",
        include_bytes!("../../assets/file-icons/mocha/folder_moonrepo.svg"),
    ),
    (
        "folder_moonrepo_open",
        include_bytes!("../../assets/file-icons/mocha/folder_moonrepo_open.svg"),
    ),
    (
        "folder_next",
        include_bytes!("../../assets/file-icons/mocha/folder_next.svg"),
    ),
    (
        "folder_next_open",
        include_bytes!("../../assets/file-icons/mocha/folder_next_open.svg"),
    ),
    (
        "folder_nix",
        include_bytes!("../../assets/file-icons/mocha/folder_nix.svg"),
    ),
    (
        "folder_nix_open",
        include_bytes!("../../assets/file-icons/mocha/folder_nix_open.svg"),
    ),
    (
        "folder_node",
        include_bytes!("../../assets/file-icons/mocha/folder_node.svg"),
    ),
    (
        "folder_node_open",
        include_bytes!("../../assets/file-icons/mocha/folder_node_open.svg"),
    ),
    (
        "folder_nuxt",
        include_bytes!("../../assets/file-icons/mocha/folder_nuxt.svg"),
    ),
    (
        "folder_nuxt_open",
        include_bytes!("../../assets/file-icons/mocha/folder_nuxt_open.svg"),
    ),
    (
        "folder_packages",
        include_bytes!("../../assets/file-icons/mocha/folder_packages.svg"),
    ),
    (
        "folder_packages_open",
        include_bytes!("../../assets/file-icons/mocha/folder_packages_open.svg"),
    ),
    (
        "folder_pesde",
        include_bytes!("../../assets/file-icons/mocha/folder_pesde.svg"),
    ),
    (
        "folder_pesde_open",
        include_bytes!("../../assets/file-icons/mocha/folder_pesde_open.svg"),
    ),
    (
        "folder_plugins",
        include_bytes!("../../assets/file-icons/mocha/folder_plugins.svg"),
    ),
    (
        "folder_plugins_open",
        include_bytes!("../../assets/file-icons/mocha/folder_plugins_open.svg"),
    ),
    (
        "folder_pre-commit",
        include_bytes!("../../assets/file-icons/mocha/folder_pre-commit.svg"),
    ),
    (
        "folder_pre-commit_open",
        include_bytes!("../../assets/file-icons/mocha/folder_pre-commit_open.svg"),
    ),
    (
        "folder_prisma",
        include_bytes!("../../assets/file-icons/mocha/folder_prisma.svg"),
    ),
    (
        "folder_prisma_open",
        include_bytes!("../../assets/file-icons/mocha/folder_prisma_open.svg"),
    ),
    (
        "folder_private",
        include_bytes!("../../assets/file-icons/mocha/folder_private.svg"),
    ),
    (
        "folder_private_open",
        include_bytes!("../../assets/file-icons/mocha/folder_private_open.svg"),
    ),
    (
        "folder_proto",
        include_bytes!("../../assets/file-icons/mocha/folder_proto.svg"),
    ),
    (
        "folder_proto_open",
        include_bytes!("../../assets/file-icons/mocha/folder_proto_open.svg"),
    ),
    (
        "folder_public",
        include_bytes!("../../assets/file-icons/mocha/folder_public.svg"),
    ),
    (
        "folder_public_open",
        include_bytes!("../../assets/file-icons/mocha/folder_public_open.svg"),
    ),
    (
        "folder_queue",
        include_bytes!("../../assets/file-icons/mocha/folder_queue.svg"),
    ),
    (
        "folder_queue_open",
        include_bytes!("../../assets/file-icons/mocha/folder_queue_open.svg"),
    ),
    (
        "folder_redux",
        include_bytes!("../../assets/file-icons/mocha/folder_redux.svg"),
    ),
    (
        "folder_redux_open",
        include_bytes!("../../assets/file-icons/mocha/folder_redux_open.svg"),
    ),
    (
        "folder_renovate",
        include_bytes!("../../assets/file-icons/mocha/folder_renovate.svg"),
    ),
    (
        "folder_renovate_open",
        include_bytes!("../../assets/file-icons/mocha/folder_renovate_open.svg"),
    ),
    (
        "folder_roblox",
        include_bytes!("../../assets/file-icons/mocha/folder_roblox.svg"),
    ),
    (
        "folder_roblox_open",
        include_bytes!("../../assets/file-icons/mocha/folder_roblox_open.svg"),
    ),
    (
        "folder_routes",
        include_bytes!("../../assets/file-icons/mocha/folder_routes.svg"),
    ),
    (
        "folder_routes_open",
        include_bytes!("../../assets/file-icons/mocha/folder_routes_open.svg"),
    ),
    (
        "folder_sass",
        include_bytes!("../../assets/file-icons/mocha/folder_sass.svg"),
    ),
    (
        "folder_sass_open",
        include_bytes!("../../assets/file-icons/mocha/folder_sass_open.svg"),
    ),
    (
        "folder_scripts",
        include_bytes!("../../assets/file-icons/mocha/folder_scripts.svg"),
    ),
    (
        "folder_scripts_open",
        include_bytes!("../../assets/file-icons/mocha/folder_scripts_open.svg"),
    ),
    (
        "folder_security",
        include_bytes!("../../assets/file-icons/mocha/folder_security.svg"),
    ),
    (
        "folder_security_open",
        include_bytes!("../../assets/file-icons/mocha/folder_security_open.svg"),
    ),
    (
        "folder_server",
        include_bytes!("../../assets/file-icons/mocha/folder_server.svg"),
    ),
    (
        "folder_server_open",
        include_bytes!("../../assets/file-icons/mocha/folder_server_open.svg"),
    ),
    (
        "folder_shared",
        include_bytes!("../../assets/file-icons/mocha/folder_shared.svg"),
    ),
    (
        "folder_shared_open",
        include_bytes!("../../assets/file-icons/mocha/folder_shared_open.svg"),
    ),
    (
        "folder_src",
        include_bytes!("../../assets/file-icons/mocha/folder_src.svg"),
    ),
    (
        "folder_src_open",
        include_bytes!("../../assets/file-icons/mocha/folder_src_open.svg"),
    ),
    (
        "folder_storybook",
        include_bytes!("../../assets/file-icons/mocha/folder_storybook.svg"),
    ),
    (
        "folder_storybook_open",
        include_bytes!("../../assets/file-icons/mocha/folder_storybook_open.svg"),
    ),
    (
        "folder_styles",
        include_bytes!("../../assets/file-icons/mocha/folder_styles.svg"),
    ),
    (
        "folder_styles_open",
        include_bytes!("../../assets/file-icons/mocha/folder_styles_open.svg"),
    ),
    (
        "folder_svg",
        include_bytes!("../../assets/file-icons/mocha/folder_svg.svg"),
    ),
    (
        "folder_svg_open",
        include_bytes!("../../assets/file-icons/mocha/folder_svg_open.svg"),
    ),
    (
        "folder_tauri",
        include_bytes!("../../assets/file-icons/mocha/folder_tauri.svg"),
    ),
    (
        "folder_tauri_open",
        include_bytes!("../../assets/file-icons/mocha/folder_tauri_open.svg"),
    ),
    (
        "folder_temp",
        include_bytes!("../../assets/file-icons/mocha/folder_temp.svg"),
    ),
    (
        "folder_temp_open",
        include_bytes!("../../assets/file-icons/mocha/folder_temp_open.svg"),
    ),
    (
        "folder_templates",
        include_bytes!("../../assets/file-icons/mocha/folder_templates.svg"),
    ),
    (
        "folder_templates_open",
        include_bytes!("../../assets/file-icons/mocha/folder_templates_open.svg"),
    ),
    (
        "folder_tests",
        include_bytes!("../../assets/file-icons/mocha/folder_tests.svg"),
    ),
    (
        "folder_tests_open",
        include_bytes!("../../assets/file-icons/mocha/folder_tests_open.svg"),
    ),
    (
        "folder_themes",
        include_bytes!("../../assets/file-icons/mocha/folder_themes.svg"),
    ),
    (
        "folder_themes_open",
        include_bytes!("../../assets/file-icons/mocha/folder_themes_open.svg"),
    ),
    (
        "folder_turbo",
        include_bytes!("../../assets/file-icons/mocha/folder_turbo.svg"),
    ),
    (
        "folder_turbo_open",
        include_bytes!("../../assets/file-icons/mocha/folder_turbo_open.svg"),
    ),
    (
        "folder_types",
        include_bytes!("../../assets/file-icons/mocha/folder_types.svg"),
    ),
    (
        "folder_types_open",
        include_bytes!("../../assets/file-icons/mocha/folder_types_open.svg"),
    ),
    (
        "folder_upload",
        include_bytes!("../../assets/file-icons/mocha/folder_upload.svg"),
    ),
    (
        "folder_upload_open",
        include_bytes!("../../assets/file-icons/mocha/folder_upload_open.svg"),
    ),
    (
        "folder_utils",
        include_bytes!("../../assets/file-icons/mocha/folder_utils.svg"),
    ),
    (
        "folder_utils_open",
        include_bytes!("../../assets/file-icons/mocha/folder_utils_open.svg"),
    ),
    (
        "folder_vercel",
        include_bytes!("../../assets/file-icons/mocha/folder_vercel.svg"),
    ),
    (
        "folder_vercel_open",
        include_bytes!("../../assets/file-icons/mocha/folder_vercel_open.svg"),
    ),
    (
        "folder_video",
        include_bytes!("../../assets/file-icons/mocha/folder_video.svg"),
    ),
    (
        "folder_video_open",
        include_bytes!("../../assets/file-icons/mocha/folder_video_open.svg"),
    ),
    (
        "folder_views",
        include_bytes!("../../assets/file-icons/mocha/folder_views.svg"),
    ),
    (
        "folder_views_open",
        include_bytes!("../../assets/file-icons/mocha/folder_views_open.svg"),
    ),
    (
        "folder_vscode",
        include_bytes!("../../assets/file-icons/mocha/folder_vscode.svg"),
    ),
    (
        "folder_vscode_open",
        include_bytes!("../../assets/file-icons/mocha/folder_vscode_open.svg"),
    ),
    (
        "folder_windows",
        include_bytes!("../../assets/file-icons/mocha/folder_windows.svg"),
    ),
    (
        "folder_windows_open",
        include_bytes!("../../assets/file-icons/mocha/folder_windows_open.svg"),
    ),
    (
        "folder_workflows",
        include_bytes!("../../assets/file-icons/mocha/folder_workflows.svg"),
    ),
    (
        "folder_workflows_open",
        include_bytes!("../../assets/file-icons/mocha/folder_workflows_open.svg"),
    ),
    (
        "folder_wxt",
        include_bytes!("../../assets/file-icons/mocha/folder_wxt.svg"),
    ),
    (
        "folder_wxt_open",
        include_bytes!("../../assets/file-icons/mocha/folder_wxt_open.svg"),
    ),
    (
        "folder_xcode",
        include_bytes!("../../assets/file-icons/mocha/folder_xcode.svg"),
    ),
    (
        "folder_xcode_open",
        include_bytes!("../../assets/file-icons/mocha/folder_xcode_open.svg"),
    ),
    (
        "folder_xmake",
        include_bytes!("../../assets/file-icons/mocha/folder_xmake.svg"),
    ),
    (
        "folder_xmake_open",
        include_bytes!("../../assets/file-icons/mocha/folder_xmake_open.svg"),
    ),
    (
        "folder_yarn",
        include_bytes!("../../assets/file-icons/mocha/folder_yarn.svg"),
    ),
    (
        "folder_yarn_open",
        include_bytes!("../../assets/file-icons/mocha/folder_yarn_open.svg"),
    ),
    (
        "font",
        include_bytes!("../../assets/file-icons/mocha/font.svg"),
    ),
    (
        "foreman",
        include_bytes!("../../assets/file-icons/mocha/foreman.svg"),
    ),
    (
        "fortran",
        include_bytes!("../../assets/file-icons/mocha/fortran.svg"),
    ),
    (
        "fsharp",
        include_bytes!("../../assets/file-icons/mocha/fsharp.svg"),
    ),
    (
        "fvm",
        include_bytes!("../../assets/file-icons/mocha/fvm.svg"),
    ),
    (
        "gatsby",
        include_bytes!("../../assets/file-icons/mocha/gatsby.svg"),
    ),
    (
        "gcp",
        include_bytes!("../../assets/file-icons/mocha/gcp.svg"),
    ),
    (
        "git",
        include_bytes!("../../assets/file-icons/mocha/git.svg"),
    ),
    (
        "git-cliff",
        include_bytes!("../../assets/file-icons/mocha/git-cliff.svg"),
    ),
    (
        "gitlab",
        include_bytes!("../../assets/file-icons/mocha/gitlab.svg"),
    ),
    (
        "gitpod",
        include_bytes!("../../assets/file-icons/mocha/gitpod.svg"),
    ),
    (
        "gleam",
        include_bytes!("../../assets/file-icons/mocha/gleam.svg"),
    ),
    (
        "gleam-config",
        include_bytes!("../../assets/file-icons/mocha/gleam-config.svg"),
    ),
    ("go", include_bytes!("../../assets/file-icons/mocha/go.svg")),
    (
        "go-mod",
        include_bytes!("../../assets/file-icons/mocha/go-mod.svg"),
    ),
    (
        "go-template",
        include_bytes!("../../assets/file-icons/mocha/go-template.svg"),
    ),
    (
        "godot",
        include_bytes!("../../assets/file-icons/mocha/godot.svg"),
    ),
    (
        "godot-assets",
        include_bytes!("../../assets/file-icons/mocha/godot-assets.svg"),
    ),
    (
        "gradle",
        include_bytes!("../../assets/file-icons/mocha/gradle.svg"),
    ),
    (
        "graphql",
        include_bytes!("../../assets/file-icons/mocha/graphql.svg"),
    ),
    (
        "groovy",
        include_bytes!("../../assets/file-icons/mocha/groovy.svg"),
    ),
    (
        "gulp",
        include_bytes!("../../assets/file-icons/mocha/gulp.svg"),
    ),
    (
        "hacking",
        include_bytes!("../../assets/file-icons/mocha/hacking.svg"),
    ),
    (
        "haml",
        include_bytes!("../../assets/file-icons/mocha/haml.svg"),
    ),
    (
        "handlebars",
        include_bytes!("../../assets/file-icons/mocha/handlebars.svg"),
    ),
    (
        "hardhat",
        include_bytes!("../../assets/file-icons/mocha/hardhat.svg"),
    ),
    (
        "hare",
        include_bytes!("../../assets/file-icons/mocha/hare.svg"),
    ),
    (
        "haskell",
        include_bytes!("../../assets/file-icons/mocha/haskell.svg"),
    ),
    (
        "haxe",
        include_bytes!("../../assets/file-icons/mocha/haxe.svg"),
    ),
    (
        "helm",
        include_bytes!("../../assets/file-icons/mocha/helm.svg"),
    ),
    (
        "heroku",
        include_bytes!("../../assets/file-icons/mocha/heroku.svg"),
    ),
    (
        "histoire",
        include_bytes!("../../assets/file-icons/mocha/histoire.svg"),
    ),
    (
        "html",
        include_bytes!("../../assets/file-icons/mocha/html.svg"),
    ),
    (
        "http",
        include_bytes!("../../assets/file-icons/mocha/http.svg"),
    ),
    (
        "huff",
        include_bytes!("../../assets/file-icons/mocha/huff.svg"),
    ),
    (
        "hugo",
        include_bytes!("../../assets/file-icons/mocha/hugo.svg"),
    ),
    (
        "humans",
        include_bytes!("../../assets/file-icons/mocha/humans.svg"),
    ),
    (
        "husky",
        include_bytes!("../../assets/file-icons/mocha/husky.svg"),
    ),
    (
        "image",
        include_bytes!("../../assets/file-icons/mocha/image.svg"),
    ),
    (
        "ionic",
        include_bytes!("../../assets/file-icons/mocha/ionic.svg"),
    ),
    (
        "java",
        include_bytes!("../../assets/file-icons/mocha/java.svg"),
    ),
    (
        "java-class",
        include_bytes!("../../assets/file-icons/mocha/java-class.svg"),
    ),
    (
        "java-jar",
        include_bytes!("../../assets/file-icons/mocha/java-jar.svg"),
    ),
    (
        "javascript",
        include_bytes!("../../assets/file-icons/mocha/javascript.svg"),
    ),
    (
        "javascript-config",
        include_bytes!("../../assets/file-icons/mocha/javascript-config.svg"),
    ),
    (
        "javascript-map",
        include_bytes!("../../assets/file-icons/mocha/javascript-map.svg"),
    ),
    (
        "javascript-react",
        include_bytes!("../../assets/file-icons/mocha/javascript-react.svg"),
    ),
    (
        "javascript-test",
        include_bytes!("../../assets/file-icons/mocha/javascript-test.svg"),
    ),
    (
        "jest",
        include_bytes!("../../assets/file-icons/mocha/jest.svg"),
    ),
    (
        "jinja",
        include_bytes!("../../assets/file-icons/mocha/jinja.svg"),
    ),
    (
        "json",
        include_bytes!("../../assets/file-icons/mocha/json.svg"),
    ),
    (
        "json-schema",
        include_bytes!("../../assets/file-icons/mocha/json-schema.svg"),
    ),
    (
        "juce",
        include_bytes!("../../assets/file-icons/mocha/juce.svg"),
    ),
    (
        "jule",
        include_bytes!("../../assets/file-icons/mocha/jule.svg"),
    ),
    (
        "julia",
        include_bytes!("../../assets/file-icons/mocha/julia.svg"),
    ),
    (
        "jupyter",
        include_bytes!("../../assets/file-icons/mocha/jupyter.svg"),
    ),
    (
        "just",
        include_bytes!("../../assets/file-icons/mocha/just.svg"),
    ),
    (
        "kdl",
        include_bytes!("../../assets/file-icons/mocha/kdl.svg"),
    ),
    (
        "key",
        include_bytes!("../../assets/file-icons/mocha/key.svg"),
    ),
    (
        "knip",
        include_bytes!("../../assets/file-icons/mocha/knip.svg"),
    ),
    (
        "kotlin",
        include_bytes!("../../assets/file-icons/mocha/kotlin.svg"),
    ),
    (
        "laravel",
        include_bytes!("../../assets/file-icons/mocha/laravel.svg"),
    ),
    (
        "latex",
        include_bytes!("../../assets/file-icons/mocha/latex.svg"),
    ),
    (
        "latte",
        include_bytes!("../../assets/file-icons/mocha/latte.svg"),
    ),
    (
        "lerna",
        include_bytes!("../../assets/file-icons/mocha/lerna.svg"),
    ),
    (
        "less",
        include_bytes!("../../assets/file-icons/mocha/less.svg"),
    ),
    (
        "lib",
        include_bytes!("../../assets/file-icons/mocha/lib.svg"),
    ),
    (
        "license",
        include_bytes!("../../assets/file-icons/mocha/license.svg"),
    ),
    (
        "lint-staged",
        include_bytes!("../../assets/file-icons/mocha/lint-staged.svg"),
    ),
    (
        "liquid",
        include_bytes!("../../assets/file-icons/mocha/liquid.svg"),
    ),
    (
        "lisp",
        include_bytes!("../../assets/file-icons/mocha/lisp.svg"),
    ),
    (
        "lock",
        include_bytes!("../../assets/file-icons/mocha/lock.svg"),
    ),
    (
        "log",
        include_bytes!("../../assets/file-icons/mocha/log.svg"),
    ),
    (
        "lua",
        include_bytes!("../../assets/file-icons/mocha/lua.svg"),
    ),
    (
        "lua-check",
        include_bytes!("../../assets/file-icons/mocha/lua-check.svg"),
    ),
    (
        "lua-client",
        include_bytes!("../../assets/file-icons/mocha/lua-client.svg"),
    ),
    (
        "lua-rocks",
        include_bytes!("../../assets/file-icons/mocha/lua-rocks.svg"),
    ),
    (
        "lua-server",
        include_bytes!("../../assets/file-icons/mocha/lua-server.svg"),
    ),
    (
        "lua-test",
        include_bytes!("../../assets/file-icons/mocha/lua-test.svg"),
    ),
    (
        "luau",
        include_bytes!("../../assets/file-icons/mocha/luau.svg"),
    ),
    (
        "luau-check",
        include_bytes!("../../assets/file-icons/mocha/luau-check.svg"),
    ),
    (
        "luau-client",
        include_bytes!("../../assets/file-icons/mocha/luau-client.svg"),
    ),
    (
        "luau-config",
        include_bytes!("../../assets/file-icons/mocha/luau-config.svg"),
    ),
    (
        "luau-server",
        include_bytes!("../../assets/file-icons/mocha/luau-server.svg"),
    ),
    (
        "luau-test",
        include_bytes!("../../assets/file-icons/mocha/luau-test.svg"),
    ),
    (
        "macos",
        include_bytes!("../../assets/file-icons/mocha/macos.svg"),
    ),
    (
        "makefile",
        include_bytes!("../../assets/file-icons/mocha/makefile.svg"),
    ),
    (
        "mantle",
        include_bytes!("../../assets/file-icons/mocha/mantle.svg"),
    ),
    (
        "markdown",
        include_bytes!("../../assets/file-icons/mocha/markdown.svg"),
    ),
    (
        "markdown-mdx",
        include_bytes!("../../assets/file-icons/mocha/markdown-mdx.svg"),
    ),
    (
        "marko",
        include_bytes!("../../assets/file-icons/mocha/marko.svg"),
    ),
    (
        "matlab",
        include_bytes!("../../assets/file-icons/mocha/matlab.svg"),
    ),
    (
        "mdbook",
        include_bytes!("../../assets/file-icons/mocha/mdbook.svg"),
    ),
    (
        "mermaid",
        include_bytes!("../../assets/file-icons/mocha/mermaid.svg"),
    ),
    (
        "meson",
        include_bytes!("../../assets/file-icons/mocha/meson.svg"),
    ),
    (
        "midi",
        include_bytes!("../../assets/file-icons/mocha/midi.svg"),
    ),
    (
        "mjml",
        include_bytes!("../../assets/file-icons/mocha/mjml.svg"),
    ),
    (
        "modernizr",
        include_bytes!("../../assets/file-icons/mocha/modernizr.svg"),
    ),
    (
        "moonrepo",
        include_bytes!("../../assets/file-icons/mocha/moonrepo.svg"),
    ),
    (
        "moonwave",
        include_bytes!("../../assets/file-icons/mocha/moonwave.svg"),
    ),
    (
        "ms-excel",
        include_bytes!("../../assets/file-icons/mocha/ms-excel.svg"),
    ),
    (
        "ms-powerpoint",
        include_bytes!("../../assets/file-icons/mocha/ms-powerpoint.svg"),
    ),
    (
        "ms-word",
        include_bytes!("../../assets/file-icons/mocha/ms-word.svg"),
    ),
    (
        "msbuild",
        include_bytes!("../../assets/file-icons/mocha/msbuild.svg"),
    ),
    (
        "nativescript",
        include_bytes!("../../assets/file-icons/mocha/nativescript.svg"),
    ),
    (
        "nest",
        include_bytes!("../../assets/file-icons/mocha/nest.svg"),
    ),
    (
        "netlify",
        include_bytes!("../../assets/file-icons/mocha/netlify.svg"),
    ),
    (
        "next",
        include_bytes!("../../assets/file-icons/mocha/next.svg"),
    ),
    (
        "nextflow",
        include_bytes!("../../assets/file-icons/mocha/nextflow.svg"),
    ),
    (
        "nginx",
        include_bytes!("../../assets/file-icons/mocha/nginx.svg"),
    ),
    (
        "nim",
        include_bytes!("../../assets/file-icons/mocha/nim.svg"),
    ),
    (
        "ninja",
        include_bytes!("../../assets/file-icons/mocha/ninja.svg"),
    ),
    (
        "nix",
        include_bytes!("../../assets/file-icons/mocha/nix.svg"),
    ),
    (
        "nix-lock",
        include_bytes!("../../assets/file-icons/mocha/nix-lock.svg"),
    ),
    (
        "nodemon",
        include_bytes!("../../assets/file-icons/mocha/nodemon.svg"),
    ),
    (
        "npm",
        include_bytes!("../../assets/file-icons/mocha/npm.svg"),
    ),
    (
        "npm-ignore",
        include_bytes!("../../assets/file-icons/mocha/npm-ignore.svg"),
    ),
    (
        "npm-lock",
        include_bytes!("../../assets/file-icons/mocha/npm-lock.svg"),
    ),
    (
        "nuget",
        include_bytes!("../../assets/file-icons/mocha/nuget.svg"),
    ),
    (
        "nunjucks",
        include_bytes!("../../assets/file-icons/mocha/nunjucks.svg"),
    ),
    (
        "nuxt",
        include_bytes!("../../assets/file-icons/mocha/nuxt.svg"),
    ),
    (
        "nuxt-ignore",
        include_bytes!("../../assets/file-icons/mocha/nuxt-ignore.svg"),
    ),
    ("nx", include_bytes!("../../assets/file-icons/mocha/nx.svg")),
    (
        "nx-ignore",
        include_bytes!("../../assets/file-icons/mocha/nx-ignore.svg"),
    ),
    (
        "ocaml",
        include_bytes!("../../assets/file-icons/mocha/ocaml.svg"),
    ),
    (
        "odin",
        include_bytes!("../../assets/file-icons/mocha/odin.svg"),
    ),
    (
        "opentofu",
        include_bytes!("../../assets/file-icons/mocha/opentofu.svg"),
    ),
    (
        "org",
        include_bytes!("../../assets/file-icons/mocha/org.svg"),
    ),
    (
        "package-json",
        include_bytes!("../../assets/file-icons/mocha/package-json.svg"),
    ),
    (
        "panda-css",
        include_bytes!("../../assets/file-icons/mocha/panda-css.svg"),
    ),
    (
        "pdf",
        include_bytes!("../../assets/file-icons/mocha/pdf.svg"),
    ),
    (
        "perl",
        include_bytes!("../../assets/file-icons/mocha/perl.svg"),
    ),
    (
        "pesde",
        include_bytes!("../../assets/file-icons/mocha/pesde.svg"),
    ),
    (
        "pesde-lock",
        include_bytes!("../../assets/file-icons/mocha/pesde-lock.svg"),
    ),
    (
        "php",
        include_bytes!("../../assets/file-icons/mocha/php.svg"),
    ),
    (
        "phrase",
        include_bytes!("../../assets/file-icons/mocha/phrase.svg"),
    ),
    (
        "phtml",
        include_bytes!("../../assets/file-icons/mocha/phtml.svg"),
    ),
    (
        "pixi",
        include_bytes!("../../assets/file-icons/mocha/pixi.svg"),
    ),
    (
        "pixi-lock",
        include_bytes!("../../assets/file-icons/mocha/pixi-lock.svg"),
    ),
    (
        "plantuml",
        include_bytes!("../../assets/file-icons/mocha/plantuml.svg"),
    ),
    (
        "playwright",
        include_bytes!("../../assets/file-icons/mocha/playwright.svg"),
    ),
    (
        "plop",
        include_bytes!("../../assets/file-icons/mocha/plop.svg"),
    ),
    (
        "pnpm",
        include_bytes!("../../assets/file-icons/mocha/pnpm.svg"),
    ),
    (
        "pnpm-lock",
        include_bytes!("../../assets/file-icons/mocha/pnpm-lock.svg"),
    ),
    (
        "poetry-lock",
        include_bytes!("../../assets/file-icons/mocha/poetry-lock.svg"),
    ),
    (
        "postcss",
        include_bytes!("../../assets/file-icons/mocha/postcss.svg"),
    ),
    (
        "powershell",
        include_bytes!("../../assets/file-icons/mocha/powershell.svg"),
    ),
    (
        "pre-commit",
        include_bytes!("../../assets/file-icons/mocha/pre-commit.svg"),
    ),
    (
        "premake",
        include_bytes!("../../assets/file-icons/mocha/premake.svg"),
    ),
    (
        "prettier",
        include_bytes!("../../assets/file-icons/mocha/prettier.svg"),
    ),
    (
        "prettier-ignore",
        include_bytes!("../../assets/file-icons/mocha/prettier-ignore.svg"),
    ),
    (
        "prisma",
        include_bytes!("../../assets/file-icons/mocha/prisma.svg"),
    ),
    (
        "prolog",
        include_bytes!("../../assets/file-icons/mocha/prolog.svg"),
    ),
    (
        "properties",
        include_bytes!("../../assets/file-icons/mocha/properties.svg"),
    ),
    (
        "proto",
        include_bytes!("../../assets/file-icons/mocha/proto.svg"),
    ),
    (
        "prototools",
        include_bytes!("../../assets/file-icons/mocha/prototools.svg"),
    ),
    (
        "pug",
        include_bytes!("../../assets/file-icons/mocha/pug.svg"),
    ),
    (
        "puppet",
        include_bytes!("../../assets/file-icons/mocha/puppet.svg"),
    ),
    (
        "puppeteer",
        include_bytes!("../../assets/file-icons/mocha/puppeteer.svg"),
    ),
    (
        "python",
        include_bytes!("../../assets/file-icons/mocha/python.svg"),
    ),
    (
        "python-compiled",
        include_bytes!("../../assets/file-icons/mocha/python-compiled.svg"),
    ),
    (
        "python-config",
        include_bytes!("../../assets/file-icons/mocha/python-config.svg"),
    ),
    ("r", include_bytes!("../../assets/file-icons/mocha/r.svg")),
    (
        "racket",
        include_bytes!("../../assets/file-icons/mocha/racket.svg"),
    ),
    (
        "razor",
        include_bytes!("../../assets/file-icons/mocha/razor.svg"),
    ),
    (
        "rdata",
        include_bytes!("../../assets/file-icons/mocha/rdata.svg"),
    ),
    (
        "readme",
        include_bytes!("../../assets/file-icons/mocha/readme.svg"),
    ),
    (
        "reason",
        include_bytes!("../../assets/file-icons/mocha/reason.svg"),
    ),
    (
        "redwood",
        include_bytes!("../../assets/file-icons/mocha/redwood.svg"),
    ),
    (
        "release",
        include_bytes!("../../assets/file-icons/mocha/release.svg"),
    ),
    (
        "remix",
        include_bytes!("../../assets/file-icons/mocha/remix.svg"),
    ),
    (
        "renovate",
        include_bytes!("../../assets/file-icons/mocha/renovate.svg"),
    ),
    (
        "rescript",
        include_bytes!("../../assets/file-icons/mocha/rescript.svg"),
    ),
    (
        "rmd",
        include_bytes!("../../assets/file-icons/mocha/rmd.svg"),
    ),
    (
        "roblox",
        include_bytes!("../../assets/file-icons/mocha/roblox.svg"),
    ),
    (
        "robots",
        include_bytes!("../../assets/file-icons/mocha/robots.svg"),
    ),
    (
        "rocket",
        include_bytes!("../../assets/file-icons/mocha/rocket.svg"),
    ),
    (
        "rokit",
        include_bytes!("../../assets/file-icons/mocha/rokit.svg"),
    ),
    (
        "rollup",
        include_bytes!("../../assets/file-icons/mocha/rollup.svg"),
    ),
    (
        "rproj",
        include_bytes!("../../assets/file-icons/mocha/rproj.svg"),
    ),
    (
        "rsml",
        include_bytes!("../../assets/file-icons/mocha/rsml.svg"),
    ),
    (
        "ruby",
        include_bytes!("../../assets/file-icons/mocha/ruby.svg"),
    ),
    (
        "ruby-gem",
        include_bytes!("../../assets/file-icons/mocha/ruby-gem.svg"),
    ),
    (
        "ruby-gem-lock",
        include_bytes!("../../assets/file-icons/mocha/ruby-gem-lock.svg"),
    ),
    (
        "ruff",
        include_bytes!("../../assets/file-icons/mocha/ruff.svg"),
    ),
    (
        "rust",
        include_bytes!("../../assets/file-icons/mocha/rust.svg"),
    ),
    (
        "rust-config",
        include_bytes!("../../assets/file-icons/mocha/rust-config.svg"),
    ),
    (
        "salesforce",
        include_bytes!("../../assets/file-icons/mocha/salesforce.svg"),
    ),
    (
        "sass",
        include_bytes!("../../assets/file-icons/mocha/sass.svg"),
    ),
    (
        "scala",
        include_bytes!("../../assets/file-icons/mocha/scala.svg"),
    ),
    (
        "scheme",
        include_bytes!("../../assets/file-icons/mocha/scheme.svg"),
    ),
    (
        "search",
        include_bytes!("../../assets/file-icons/mocha/search.svg"),
    ),
    (
        "security",
        include_bytes!("../../assets/file-icons/mocha/security.svg"),
    ),
    (
        "semantic-release",
        include_bytes!("../../assets/file-icons/mocha/semantic-release.svg"),
    ),
    (
        "semgrep",
        include_bytes!("../../assets/file-icons/mocha/semgrep.svg"),
    ),
    (
        "semgrep-ignore",
        include_bytes!("../../assets/file-icons/mocha/semgrep-ignore.svg"),
    ),
    (
        "sentry",
        include_bytes!("../../assets/file-icons/mocha/sentry.svg"),
    ),
    (
        "serverless",
        include_bytes!("../../assets/file-icons/mocha/serverless.svg"),
    ),
    (
        "shader",
        include_bytes!("../../assets/file-icons/mocha/shader.svg"),
    ),
    (
        "sketch",
        include_bytes!("../../assets/file-icons/mocha/sketch.svg"),
    ),
    (
        "slidesk",
        include_bytes!("../../assets/file-icons/mocha/slidesk.svg"),
    ),
    (
        "snowpack",
        include_bytes!("../../assets/file-icons/mocha/snowpack.svg"),
    ),
    (
        "solidity",
        include_bytes!("../../assets/file-icons/mocha/solidity.svg"),
    ),
    (
        "sonar-cloud",
        include_bytes!("../../assets/file-icons/mocha/sonar-cloud.svg"),
    ),
    (
        "spwn",
        include_bytes!("../../assets/file-icons/mocha/spwn.svg"),
    ),
    (
        "squirrel",
        include_bytes!("../../assets/file-icons/mocha/squirrel.svg"),
    ),
    (
        "stackblitz",
        include_bytes!("../../assets/file-icons/mocha/stackblitz.svg"),
    ),
    (
        "stata",
        include_bytes!("../../assets/file-icons/mocha/stata.svg"),
    ),
    (
        "stencil",
        include_bytes!("../../assets/file-icons/mocha/stencil.svg"),
    ),
    (
        "stitches",
        include_bytes!("../../assets/file-icons/mocha/stitches.svg"),
    ),
    (
        "storybook",
        include_bytes!("../../assets/file-icons/mocha/storybook.svg"),
    ),
    (
        "storybook-svelte",
        include_bytes!("../../assets/file-icons/mocha/storybook-svelte.svg"),
    ),
    (
        "storybook-vue",
        include_bytes!("../../assets/file-icons/mocha/storybook-vue.svg"),
    ),
    (
        "stylelint",
        include_bytes!("../../assets/file-icons/mocha/stylelint.svg"),
    ),
    (
        "stylelint-ignore",
        include_bytes!("../../assets/file-icons/mocha/stylelint-ignore.svg"),
    ),
    (
        "stylua",
        include_bytes!("../../assets/file-icons/mocha/stylua.svg"),
    ),
    (
        "stylua-ignore",
        include_bytes!("../../assets/file-icons/mocha/stylua-ignore.svg"),
    ),
    (
        "sublime",
        include_bytes!("../../assets/file-icons/mocha/sublime.svg"),
    ),
    (
        "super-collider",
        include_bytes!("../../assets/file-icons/mocha/super-collider.svg"),
    ),
    (
        "svelte",
        include_bytes!("../../assets/file-icons/mocha/svelte.svg"),
    ),
    (
        "svelte-config",
        include_bytes!("../../assets/file-icons/mocha/svelte-config.svg"),
    ),
    (
        "svg",
        include_bytes!("../../assets/file-icons/mocha/svg.svg"),
    ),
    (
        "swift",
        include_bytes!("../../assets/file-icons/mocha/swift.svg"),
    ),
    (
        "swiftformat",
        include_bytes!("../../assets/file-icons/mocha/swiftformat.svg"),
    ),
    (
        "tailwind",
        include_bytes!("../../assets/file-icons/mocha/tailwind.svg"),
    ),
    (
        "taskfile",
        include_bytes!("../../assets/file-icons/mocha/taskfile.svg"),
    ),
    (
        "tauri",
        include_bytes!("../../assets/file-icons/mocha/tauri.svg"),
    ),
    (
        "tauri-ignore",
        include_bytes!("../../assets/file-icons/mocha/tauri-ignore.svg"),
    ),
    (
        "terraform",
        include_bytes!("../../assets/file-icons/mocha/terraform.svg"),
    ),
    (
        "text",
        include_bytes!("../../assets/file-icons/mocha/text.svg"),
    ),
    (
        "todo",
        include_bytes!("../../assets/file-icons/mocha/todo.svg"),
    ),
    (
        "toml",
        include_bytes!("../../assets/file-icons/mocha/toml.svg"),
    ),
    (
        "turbo",
        include_bytes!("../../assets/file-icons/mocha/turbo.svg"),
    ),
    (
        "twig",
        include_bytes!("../../assets/file-icons/mocha/twig.svg"),
    ),
    (
        "twine",
        include_bytes!("../../assets/file-icons/mocha/twine.svg"),
    ),
    (
        "typescript",
        include_bytes!("../../assets/file-icons/mocha/typescript.svg"),
    ),
    (
        "typescript-config",
        include_bytes!("../../assets/file-icons/mocha/typescript-config.svg"),
    ),
    (
        "typescript-def",
        include_bytes!("../../assets/file-icons/mocha/typescript-def.svg"),
    ),
    (
        "typescript-react",
        include_bytes!("../../assets/file-icons/mocha/typescript-react.svg"),
    ),
    (
        "typescript-test",
        include_bytes!("../../assets/file-icons/mocha/typescript-test.svg"),
    ),
    (
        "typst",
        include_bytes!("../../assets/file-icons/mocha/typst.svg"),
    ),
    (
        "unity",
        include_bytes!("../../assets/file-icons/mocha/unity.svg"),
    ),
    (
        "unocss",
        include_bytes!("../../assets/file-icons/mocha/unocss.svg"),
    ),
    (
        "url",
        include_bytes!("../../assets/file-icons/mocha/url.svg"),
    ),
    ("uv", include_bytes!("../../assets/file-icons/mocha/uv.svg")),
    ("v", include_bytes!("../../assets/file-icons/mocha/v.svg")),
    (
        "vala",
        include_bytes!("../../assets/file-icons/mocha/vala.svg"),
    ),
    (
        "vanilla-extract",
        include_bytes!("../../assets/file-icons/mocha/vanilla-extract.svg"),
    ),
    (
        "vapi",
        include_bytes!("../../assets/file-icons/mocha/vapi.svg"),
    ),
    (
        "vento",
        include_bytes!("../../assets/file-icons/mocha/vento.svg"),
    ),
    (
        "vercel",
        include_bytes!("../../assets/file-icons/mocha/vercel.svg"),
    ),
    (
        "vercel-ignore",
        include_bytes!("../../assets/file-icons/mocha/vercel-ignore.svg"),
    ),
    (
        "verilog",
        include_bytes!("../../assets/file-icons/mocha/verilog.svg"),
    ),
    (
        "vhs",
        include_bytes!("../../assets/file-icons/mocha/vhs.svg"),
    ),
    (
        "video",
        include_bytes!("../../assets/file-icons/mocha/video.svg"),
    ),
    (
        "vim",
        include_bytes!("../../assets/file-icons/mocha/vim.svg"),
    ),
    (
        "visual-studio",
        include_bytes!("../../assets/file-icons/mocha/visual-studio.svg"),
    ),
    (
        "vital",
        include_bytes!("../../assets/file-icons/mocha/vital.svg"),
    ),
    (
        "vite",
        include_bytes!("../../assets/file-icons/mocha/vite.svg"),
    ),
    (
        "vitest",
        include_bytes!("../../assets/file-icons/mocha/vitest.svg"),
    ),
    (
        "vs-codium",
        include_bytes!("../../assets/file-icons/mocha/vs-codium.svg"),
    ),
    (
        "vscode",
        include_bytes!("../../assets/file-icons/mocha/vscode.svg"),
    ),
    (
        "vscode-ignore",
        include_bytes!("../../assets/file-icons/mocha/vscode-ignore.svg"),
    ),
    (
        "vue",
        include_bytes!("../../assets/file-icons/mocha/vue.svg"),
    ),
    (
        "vue-config",
        include_bytes!("../../assets/file-icons/mocha/vue-config.svg"),
    ),
    (
        "wally",
        include_bytes!("../../assets/file-icons/mocha/wally.svg"),
    ),
    (
        "web-assembly",
        include_bytes!("../../assets/file-icons/mocha/web-assembly.svg"),
    ),
    (
        "webpack",
        include_bytes!("../../assets/file-icons/mocha/webpack.svg"),
    ),
    (
        "windi",
        include_bytes!("../../assets/file-icons/mocha/windi.svg"),
    ),
    (
        "workflow",
        include_bytes!("../../assets/file-icons/mocha/workflow.svg"),
    ),
    (
        "wrangler",
        include_bytes!("../../assets/file-icons/mocha/wrangler.svg"),
    ),
    (
        "wxt",
        include_bytes!("../../assets/file-icons/mocha/wxt.svg"),
    ),
    (
        "xaml",
        include_bytes!("../../assets/file-icons/mocha/xaml.svg"),
    ),
    (
        "xcode",
        include_bytes!("../../assets/file-icons/mocha/xcode.svg"),
    ),
    (
        "xmake",
        include_bytes!("../../assets/file-icons/mocha/xmake.svg"),
    ),
    (
        "xml",
        include_bytes!("../../assets/file-icons/mocha/xml.svg"),
    ),
    (
        "yaml",
        include_bytes!("../../assets/file-icons/mocha/yaml.svg"),
    ),
    (
        "yarn",
        include_bytes!("../../assets/file-icons/mocha/yarn.svg"),
    ),
    (
        "yarn-lock",
        include_bytes!("../../assets/file-icons/mocha/yarn-lock.svg"),
    ),
    (
        "zap",
        include_bytes!("../../assets/file-icons/mocha/zap.svg"),
    ),
    (
        "zig",
        include_bytes!("../../assets/file-icons/mocha/zig.svg"),
    ),
    (
        "zip",
        include_bytes!("../../assets/file-icons/mocha/zip.svg"),
    ),
];
